version: "3"

services:
  web:
    image: nginx
    volumes:
      - ".:/app"
      - "./docker_dev/nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./docker_dev/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - php
    ports:
      - "8080:80"

  php:
    build:
      context: docker_dev/php
    volumes:
      - ".:/app"
      - "./docker_dev/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ZPt9BhRt55AjSCU&8tsj
      - POSTGRES_USER=event_nexus
      - POSTGRES_DB=event_nexus